

spring.application.name=TravelBookingApp

spring.datasource.url=jdbc:mysql://ro-db.cevgq4ic87x5.us-east-1.rds.amazonaws.com:3306/traveldb
spring.datasource.username=roshanro
spring.datasource.password=roshanro

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081
