pipeline {

    agent any

    environment {
        IMAGE_NAME = "roshan19ro/travel-booking-app"
        IMAGE_TAG  = "${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/roshanro-exe/travel-booking-app.git'
            }
        }

        stage('Build') {
            steps {
                dir('travel-booking-app') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Unit Test') {
            steps {
                dir('travel-booking-app') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('travel-booking-app') {
                    sh 'docker build -t $IMAGE_NAME:$IMAGE_TAG .'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )
                ]) {

                    sh '''
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

                        docker push $IMAGE_NAME:$IMAGE_TAG
                    '''
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                dir('travel-booking-app') {
                    sh '''
                        kubectl apply -f k8s/service.yaml

                        kubectl set image deployment/travel-booking-app \
                        travel-booking-app=$IMAGE_NAME:$IMAGE_TAG

                        kubectl rollout status deployment/travel-booking-app --timeout=180s
                    '''
                }
            }
        }

    }

    post {

        success {
            echo 'Pipeline executed successfully.'
        }

        failure {
            echo 'Pipeline failed.'
        }

    }
}

