apiVersion: apps/v1
kind: Deployment

metadata:
  name: travel-booking-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: travel-booking-app

  template:

    metadata:
      labels:
        app: travel-booking-app

    spec:

      containers:

      - name: travel-booking-app

        image: roshan19ro/travel-booking-app:4

        imagePullPolicy: Always

        ports:

        - containerPort: 8081

        env:

        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://ro-db.cevgq4ic87x5.us-east-1.rds.amazonaws.com:3306/traveldb

        - name: SPRING_DATASOURCE_USERNAME
          value: roshanro

        - name: SPRING_DATASOURCE_PASSWORD
          value: roshanro
